{{- if and .Values.talk.enabled (not .Values.talk.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud-aio.talk.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.talk.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: nextcloud-aio-talk
    app.kubernetes.io/component: secret
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  internal: {{ .Values.talk.auth.internal | b64enc }}
  signaling: {{ .Values.talk.auth.signaling | b64enc }}
  turn: {{ .Values.talk.auth.turn | b64enc }}
  recording: {{ .Values.talk.auth.recording | b64enc }}
{{- end }}