{{- if and .Values.whiteboard.enabled (not .Values.whiteboard.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud-aio.whiteboard.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.whiteboard.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: nextcloud-aio-whiteboard
    app.kubernetes.io/component: secret
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  secret: {{ .Values.whiteboard.auth.secret | b64enc }}
{{- end }}