{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud-aio.web.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: nextcloud-aio-web
    app.kubernetes.io/component: server
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.web.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/part-of: nextcloud-aio-web
      app.kubernetes.io/component: server
  template:
    metadata: 
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/part-of: nextcloud-aio-web
        app.kubernetes.io/component: server
    spec:
      initContainers:
        - name: init-volumes
          image: alpine
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
            - /nextcloud-aio-web
          volumeMounts:
            - name: nextcloud-aio-web
              mountPath: /nextcloud-aio-web
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: APACHE_MAX_SIZE
              value: "{{ .Values.web.maxSize }}"
            - name: APACHE_MAX_TIME
              value: {{ .Values.nextcloud.phpLimits.time | quote }}
            - name: APACHE_PORT
              value: "{{ .Values.web.containerPorts.https }}"
            - name: COLLABORA_HOST
              value: {{ include "nextcloud-aio.collabora.fullname" . }}
            - name: NC_DOMAIN
              value: "{{ .Values.nextcloud.domain }}"
            - name: NEXTCLOUD_HOST
              value: {{ template "nextcloud-aio.nextcloud.fullname" . }}
            - name: NOTIFY_PUSH_HOST
              value: {{ include "nextcloud-aio.notifyPush.fullname" . }}
            - name: ONLYOFFICE_HOST
              value: {{ include "nextcloud-aio.onlyOffice.fullname" . }}
            - name: TALK_HOST
              value: {{ include "nextcloud-aio.talk.fullname" . }}
            - name: TZ
              value: "{{ include "nextcloud-aio.timezone" . }}"
          image: {{ template "nextcloud-aio.web.image" . }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          name: apache
          ports:
            - name: http
              containerPort: {{ .Values.web.containerPorts.http }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.web.containerPorts.https }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-aio-nextcloud
              readOnly: true
            - mountPath: /mnt/data
              name: nextcloud-aio-web
          {{- if .Values.web.cert }}
          {{- if .Values.web.cert.existingSSL }}
            - name: nextcloud-aio-web-ssl
              mountPath: /mnt/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/{{ .Values.nextcloud.domain }}
          {{- end }}
          {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud
        - name: nextcloud-aio-web
          persistentVolumeClaim:
            claimName: nextcloud-aio-web
        {{- if .Values.web.cert }}
        {{- if .Values.web.cert.existingSSL }}
        - name: nextcloud-aio-web-ssl
          _type: hostPath
          hostPath:
            type: Directory
            path: {{ .Values.web.cert.existingSSL }}
        {{- end }}
        {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
{{- end -}}
