{{- if .Values.elasticSearch.enabled }}
{{- if .Values.elasticSearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- $versionLabel := dict "app.kubernetes.io/version" ( include "common.images.version" ( dict "imageRoot" .Values.nextcloud.image "chart" .Chart ) ) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.commonLabels $versionLabel ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: nextcloud-aio-elasticsearch
    app.kubernetes.io/component: pvc
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  name: nextcloud-aio-elasticsearch
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  {{- include "common.storage.class" (dict "persistence" .Values.elasticSearch.persistence "global" .Values.global) | nindent 2 }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticSearch.persistence.size }}
{{- end -}}
{{- end -}}